name: 'Publish CodeArtifact'
description: 'Publish the repository to codeartifact'
inputs:
  domain:
    description: "CodeArtifact Domain"
    required: true
  repo:
    description: 'CodeArtifact Repository'
    required: true
  aws-account-id:
    description: "AWS Account ID"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
      export TWINE_USERNAME=aws
      export TWINE_PASSWORD=`aws codeartifact get-authorization-token --domain ${{ inputs.domain }} --domain-owner ${{ inputs.aws-account-id }} --query authorizationToken --output text`
      export TWINE_REPOSITORY_URL=`aws codeartifact get-repository-endpoint --domain ${{ inputs.domain }} --domain-owner ${{ inputs.aws-account-id }} --repository ${{ inputs.repo }} --format pypi --query repositoryEndpoint --output text`
      python setup.py sdist bdist_wheel
      twine upload dist/*
