name: 'Publish Twine'
description: 'Publish the repository to codeartifact'
inputs:
  what-to-do:  # id of input
    description: 'What to Do'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Hello World!"
      shell: bash
    - run: echo "${{ inputs.what-to-do }}"
      shell: bash
