name: 'Publish CodeArtifact'
description: 'Publish the repository to codeartifact'
inputs:
  aws_account_id:
    description: "AWS Account ID"
    required: true
  domain:
    description: "CodeArtifact Domain"
    required: true
  repo:
    description: 'CodeArtifact Repository'
    required: true
runs:
  using: "composite"
  steps:
      - run: ${{ github.action_path }}/publisher.sh ${{ inputs.aws_account_id }} ${{ inputs.domain }} ${{ inputs.repo }}
        shell: bash
