name: 'Hello Action'
description: 'Complete some task'
inputs:
  what-to-do:  # id of input
    description: 'What to Do'
    required: true
    default: 'Config custom/private package Repo'
runs:
  using: "composite"
  steps:
    - run: echo "Hello World!"
      shell: bash
    - run: echo ${{ inputs.what-to-do }}
      shell: bash
